### ISSUE TITLE
exception in "isInActiveSprint" while pull from atlassian.net

### ISSUE THREAD

**Issue by ocoka** [ulfschneider/breakdown#111]
Hi, I've just install this extension, and, while trying to pull for first time, I've got 
```
Pulled JIRA data could not be stringified due to TypeError: data.indexOf is not a function
    at /home/ocoka/.atom/packages/breakdown/lib/breakdown-util.js:411:37
    at /home/ocoka/.atom/packages/breakdown/node_modules/underscore/underscore.js:1240:13
    at Function.find (/home/ocoka/.atom/packages/breakdown/node_modules/underscore/underscore.js:1303:15)
    at Object.isInActiveSprint (/home/ocoka/.atom/packages/breakdown/lib/breakdown-util.js:410:45)
    at Object.isInActiveSprint (/home/ocoka/.atom/packages/breakdown/lib/breakdown-stringify.js:37:48)
    at Object.stringifyActiveSprint (/home/ocoka/.atom/packages/breakdown/lib/breakdown-stringify.js:46:22)
    at Object.stringifyJiraContent (/home/ocoka/.atom/packages/breakdown/lib/breakdown-stringify.js:472:36)
    at Object.stringifyAfterPull (/home/ocoka/.atom/packages/breakdown/lib/breakdown-stringify.js:11:53)
    at /home/ocoka/.atom/packages/breakdown/lib/breakdown.js:93:
```
`sprint` field is object in my case

![CopyQ Imzaye](https://user-images.githubusercontent.com/8239290/130766612-c8b48056-214d-47c9-ae32-fe8a60cdb64b.png)

**Comment by ulfschneider** [comment]
Sorry for this fix taking so long. It was a small thing in the end.
